### ISSUE TITLE
Numpy Cannot cast ufunc multiply output from dtype on util.py

### ISSUE THREAD

**Issue by epriwahyu** [huangzj421/Binaural-WSJ0Mix#1]
Hi,
I tried to reproduce the generating data. However, I got some error due from util.py at 

line 15: samples *= scaling_factor.

I tried to revised it, become : samples = (samples * scaling_factor). Then, it works :)

**Comment by huangzj421** [comment]
Hi @epriwahyu ,
I have updated it. Much thanks!
If you got any trouble while generating it, please inform me.
